### ISSUE TITLE
Stacked bar chart 

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#142]
Need to have a variant of bar chart for this:

![image](https://cloud.githubusercontent.com/assets/1153786/19706833/e287129c-9ac8-11e6-8e5f-bc0bd9b490f5.png)

**Comment by nxanil** [comment]
@curran @ronakmshah 

Do you have some JSON data sample for such type of graphs that I can use as the base for this?
Or if you have some already built elastic query than that will be very helpful as well.

**Comment by curran** [comment]
Hi @nxanil ,

I have made this stacked bar chart in the past, which gives an idea of how it can be constructed https://bl.ocks.org/curran/0d2cc6698cad72a48027b8de0ebb417d

Also, here is a stacked bar chart using D3 version 4, where the APIs are a bit different https://bl.ocks.org/mbostock/3886208

**Comment by nxanil** [comment]
Hi @curran @ronakmshah 

First variant is really very nice, but do we have to support both the values i.e. negative and positives and is there any predefined query that I can use to start on this?

**Comment by nxanil** [comment]
Stacked Bar chart feature is already implemented
