### ISSUE TITLE
empty results on linegraph are not handled in a case where empty bucket is return

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#227]
![screen shot 2016-11-16 at 5 23 03 pm](https://cloud.githubusercontent.com/assets/1153786/20372619/626b8ce0-ac21-11e6-847a-08c70f975ab0.png)

Here, the tabify is showing 1 bucket, but it is empty. We should handle that case as well.

**Comment by nxanil** [comment]
Verified, ready to close.

**Comment by nxanil** [comment]
@ronakmshah  
Refer to PR #444. Resolved over there.
