### ISSUE TITLE
Long axis labels should be wrapped

### ISSUE THREAD

**Issue by t00f** [nuagenetworks/visualization-framework#288]
When having long axis, we are seeing some overlapping issue (See picture above).
I am wondering if we could find a generic solution to these problems ?

![screen shot 2016-12-01 at 3 14 36 pm](https://cloud.githubusercontent.com/assets/1447243/20816836/2bd0004e-b7d9-11e6-904d-68b7dbed44b6.png)

**Comment by nxanil** [comment]
@curran @ronakmshah 

Do you have any particular preference among: 
1) Showing of Ellipsis
2) Wrapping text to multiple lines - But in that case, we have to calculate the height of the label to get final chart height and in the case of very long labels, we might be left with very little vertical space.
3) Wrapping up upto two lines then showing of ellipsis...

**Comment by curran** [comment]
I'd defer to @ronakmshah 's preference on this. I agree that option 2 would be more complex.

**Comment by nxanil** [comment]
@ronakmshah 
Please suggest, what you think will be ideal in our case out of above options?

**Comment by nxanil** [comment]
@ronakmshah Please review this pull request: https://github.com/nuagenetworks/visualization-framework/pull/386

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
