### ISSUE TITLE
Line Graph is expecting timestamp as x-axis

### ISSUE THREAD

**Issue by t00f** [nuagenetworks/visualization-framework#320]
Right now, the `LineGraph` component is assuming the x-axis is a timestamp.
In the demo-vf, I made some line graph where the axis is a string.

Instead of presenting the years as "1896", ... "2012", the graph shows ".900", ".910"... by default.
I temporarily fixed the labels by adding the following:

```
"xTickFormat": "1",
```
(See [visualizations/medalsEvolution.json](https://github.com/nuagenetworks/demo-vf/blob/master/public/configurations/visualizations/medalsEvolution.json))

**Comment by nxanil** [comment]
@ronakmshah 

Review Pull request #398

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
