### ISSUE TITLE
Y-Axis does not always start with 0 in line graph

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#343]
@divyahc Can you please fill up the details with the screen shot as we had discussed yesterday?
@curran Can you please take a look on this issue once Divya provides info.

**Comment by nxanil** [comment]
@ronakmshah:

Please review pull request "#344" for the same.

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
