### ISSUE TITLE
Add Line Chart configuration option for zero baseline

### ISSUE THREAD

**Issue by curran** [nuagenetworks/visualization-framework#344]

**Comment by nxanil** [comment]
@ronakmshah:

Please review pull request "#344" for the same.

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.

**Comment by nxanil** [comment]
Added a "config parameter" named as "zeroStart". Set it to true, if you want to start the y axis from zero.
Added the same feature to MultiLine Chart as well.
