### ISSUE TITLE
Multiline chart issues

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#376]
1. Noticed an error as following appearing for the multiline chart.

![error-1](https://cloud.githubusercontent.com/assets/1153786/26472395/c587f4f2-415a-11e7-8c99-07a493964a7c.png)

2. Also, the min and max height are not set properly thus unable to see all the lines.
![error-2](https://cloud.githubusercontent.com/assets/1153786/26472396/c792341a-415a-11e7-8fb0-a1fda452982e.png)

As you can see, memory has a constant value in range of 15, but the line is not being shown. I believe it can be reproduce if the two of the three lines are having similar min max and 3rd having a little different. 
Also noticed that 2,3 and 4 as a number appearing 2 times iso one.

**Comment by nxanil** [comment]
@ronakmshah Sent a Pull request please review.

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
