### ISSUE TITLE
WIFIbranch dashboard - interaction between viz is not working as expected

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#382]
![screen shot 2017-05-31 at 11 32 54 am](https://cloud.githubusercontent.com/assets/1153786/26647740/23bee9f6-45f5-11e7-8192-4f2a3e6d68d8.png)
So the basic screen works ok. But when I click on the table's row, I am expecting two more graphs to be seemlessly appear which is not the case.
![screen shot 2017-05-31 at 11 33 01 am](https://cloud.githubusercontent.com/assets/1153786/26647751/2c320f32-45f5-11e7-8e8c-53bac33f6ddf.png)

This is especially happening after the introduction of the VariationTextGraph.
If I take them out of the dashboard, the interaction works fine.

**Comment by successivesoftware** [comment]
@ronakmshah 

I am not able to reproduce the issue at my local.
Here is the screenshot from my end:
[![https://gyazo.com/5ea87a3c5643c65262402d850f254138](https://gyazo.com/5ea87a3c5643c65262402d850f254138/raw)](https://gyazo.com/5ea87a3c5643c65262402d850f254138)


Just as a note (might be already added at your end): Earlier elasticsearch was giving me error at my end, so I have added following lines in elasticsearch.yml
```
script.engine.groovy.inline.search: true
script.inline: on
script.indexed: on
```

**Comment by nxanil** [comment]
@ronakmshah 
Completed from my side.
