### ISSUE TITLE
Multiline graph errors on vnf dashboard

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#389]
The display looks ok but i am seeing this error on console which needs to be addressed.

![screen shot 2017-06-13 at 11 40 23 am](https://user-images.githubusercontent.com/1153786/27098671-4f64b094-502d-11e7-813c-0e0a4e2ea383.png)

**Comment by nxanil** [comment]
@ronakmshah 

Please review Pulll request: "Console Warning and Errors for Multiline and Other Graphs #399"

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
