### ISSUE TITLE
Handling 0 values on the linegraph 

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#390]
![screen shot 2017-06-13 at 11 43 52 am](https://user-images.githubusercontent.com/1153786/27098798-a88b39fe-502d-11e7-945b-3368632a6729.png)

Cant show thing below 0 on Y-axis. :)

Not sure if the other PR with 0.10 padding should fix this but opening this for tracking anyways.

**Comment by nxanil** [comment]
@ronakmshah 

How can I reproduce it, any particular branch or test case?
Seems to be fine for me:
![image](https://user-images.githubusercontent.com/26645756/27171998-2585fc1a-51d1-11e7-8cec-8ce44c877d96.png)

**Comment by ronakmshah** [comment]
![screen shot 2017-06-20 at 4 00 17 pm](https://user-images.githubusercontent.com/1153786/27359618-953f99f4-55d1-11e7-88c3-8f0d01e85d40.png)


On the VNF dashboard when I change time from last 24 hr to last 15 min I can see it.

**Comment by nxanil** [comment]
@ronakmshah:

Which branch you are looking after ? Is the code updated at your end?
Here what I getting:
![image](https://user-images.githubusercontent.com/26645756/27384035-06350782-56ab-11e7-930c-64eec05cff39.png)

**Comment by nxanil** [comment]
@ronakmshah 
Please refer to Pull request: #405

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
