### ISSUE TITLE
description box needs to fit-in within the viz panel

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#401]
![screen shot 2017-06-14 at 5 23 23 pm](https://user-images.githubusercontent.com/1153786/27197011-8da907de-51c1-11e7-9ac1-8837a3d759dc.png)

If you look at the Active SSIDs VariationTextGraph, the description is shown at the bottom and outside the viz itself. This needs a fix. Use WifiBranch dashboard to reproduce this

**Comment by nxanil** [comment]
@ronakmshah 
Please review Pull Request #402
