### ISSUE TITLE
HeatMap is not displayed correctly

### ISSUE THREAD

**Issue by sayaji15** [nuagenetworks/visualization-framework#404]
HeatMap is kitchenSink dashboard fails to display with this error
`` **error TypeError: domainData.data is not a function**
Stack trace:
getMappedScaleColor@webpack:///./src/components/Graphs/AbstractGraph.js?:222:13
render@webpack:///./src/components/Graphs/HeatmapGraph/index.js?:95:25
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext/renderedComponent<@webpack:///./~/react/lib/ReactCompositeComponent.js?:793:16
measureLifeCyclePerf@webpack:///./~/react/lib/ReactCompositeComponent.js?:74:12
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext@webpack:///./~/react/lib/ReactCompositeComponent.js?:792:27
ReactCompositeComponentMixin._renderValidatedComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:819:29
ReactCompositeComponentMixin.performInitialMount@webpack:///./~/react/lib/ReactCompositeComponent.js?:361:1
ReactCompositeComponentMixin.mountComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:257:16
ReactReconciler.mountComponent@webpack:///./~/react/lib/ReactReconciler.js?:47:18
ReactChildReconciler.updateChildren@webpack:///./~/react/lib/ReactChildReconciler.js?:122:35
ReactMultiChild.Mixin._reconcilerUpdateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:210:11
ReactMultiChild.Mixin._updateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:314:26
ReactMultiChild.Mixin.updateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:301:7
ReactDOMComponent.Mixin._updateDOMChildren@webpack:///./~/react/lib/ReactDOMComponent.js?:942:7
ReactDOMComponent.Mixin.updateComponent@webpack:///./~/react/lib/ReactDOMComponent.js?:760:5
ReactDOMComponent.Mixin.receiveComponent@webpack:///./~/react/lib/ReactDOMComponent.js?:718:5
ReactReconciler.receiveComponent@webpack:///./~/react/lib/ReactReconciler.js?:126:5
ReactCompositeComponentMixin._updateRenderedComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:751:7
ReactCompositeComponentMixin._performComponentUpdate@webpack:///./~/react/lib/ReactCompositeComponent.js?:721:5
ReactCompositeComponentMixin.updateComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:642:7
ReactCompositeComponentMixin.receiveComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:544:5
ReactReconciler.receiveComponent@webpack:///./~/react/lib/ReactReconciler.js?:126:5
ReactChildReconciler.updateChildren@webpack:///./~/react/lib/ReactChildReconciler.js?:110:9
ReactMultiChild.Mixin._reconcilerUpdateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:210:11
ReactMultiChild.Mixin._updateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:314:26
ReactMultiChild.Mixin.updateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:301:7
ReactDOMComponent.Mixin._updateDOMChildren@webpack:///./~/react/lib/ReactDOMComponent.js?:942:7
ReactDOMComponent.Mixin.updateComponent@webpack:///./~/react/lib/ReactDOMComponent.js?:760:5
ReactDOMComponent.Mixin.receiveComponent@webpack:///./~/react/lib/ReactDOMComponent.js?:718:5
ReactReconciler.receiveComponent@webpack:///./~/react/lib/ReactReconciler.js?:126:5
ReactChildReconciler.updateChildren@webpack:///./~/react/lib/ReactChildReconciler.js?:110:9
ReactMultiChild.Mixin._reconcilerUpdateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:210:11
ReactMultiChild.Mixin._updateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:314:26
ReactMultiChild.Mixin.updateChildren@webpack:///./~/react/lib/ReactMultiChild.js?:301:7
ReactDOMComponent.Mixin._updateDOMChildren@webpack:///./~/react/lib/ReactDOMComponent.js?:942:7
ReactDOMComponent.Mixin.updateComponent@webpack:///./~/react/lib/ReactDOMComponent.js?:760:5
ReactDOMComponent.Mixin.receiveComponent@webpack:///./~/react/lib/ReactDOMComponent.js?:718:5
ReactReconciler.receiveComponent@webpack:///./~/react/lib/ReactReconciler.js?:126:5
ReactCompositeComponentMixin._updateRenderedComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:751:7
ReactCompositeComponentMixin._performComponentUpdate@webpack:///./~/react/lib/ReactCompositeComponent.js?:721:5
ReactCompositeComponentMixin.updateComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:642:7
ReactCompositeComponentMixin.receiveComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:544:5
ReactReconciler.receiveComponent@webpack:///./~/react/lib/ReactReconciler.js?:126:5
ReactCompositeComponentMixin._updateRenderedComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:751:7
ReactCompositeComponentMixin._performComponentUpdate@webpack:///./~/react/lib/ReactCompositeComponent.js?:721:5
ReactCompositeComponentMixin.updateComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:642:7
ReactCompositeComponentMixin.receiveComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:544:5
ReactReconciler.receiveComponent@webpack:///./~/react/lib/ReactReconciler.js?:126:5
ReactCompositeComponentMixin._updateRenderedComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:751:7
ReactCompositeComponentMixin._performComponentUpdate@webpack:///./~/react/lib/ReactCompositeComponent.js?:721:5
ReactCompositeComponentMixin.updateComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:642:7
ReactCompositeComponentMixin.receiveComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:544:5
ReactReconciler.receiveComponent@webpack:///./~/react/lib/ReactReconciler.js?:126:5
ReactCompositeComponentMixin._updateRenderedComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:751:7
ReactCompositeComponentMixin._performComponentUpdate@webpack:///./~/react/lib/ReactCompositeComponent.js?:721:5
ReactCompositeComponentMixin.updateComponent@webpack:///./~/react/lib/ReactCompositeComponent.js?:642:7
ReactCompositeComponentMixin.performUpdateIfNecessary@webpack:///./~/react/lib/ReactCompositeComponent.js?:558:7
ReactReconciler.performUpdateIfNecessary@webpack:///./~/react/lib/ReactReconciler.js?:158:5
runBatchedUpdates@webpack:///./~/react/lib/ReactUpdates.js?:151:5
Mixin.perform@webpack:///./~/react/lib/Transaction.js?:138:13
Mixin.perform@webpack:///./~/react/lib/Transaction.js?:138:13
.perform@webpack:///./~/react/lib/ReactUpdates.js?:90:12
flushBatchedUpdates@webpack:///./~/react/lib/ReactUpdates.js?:173:7
Mixin.closeAll@webpack:///./~/react/lib/Transaction.js?:204:11
Mixin.perform@webpack:///./~/react/lib/Transaction.js?:151:11
ReactDefaultBatchingStrategy.batchedUpdates@webpack:///./~/react/lib/ReactDefaultBatchingStrategy.js?:63:7
enqueueUpdate@webpack:///./~/react/lib/ReactUpdates.js?:201:5
enqueueUpdate@webpack:///./~/react/lib/ReactUpdateQueue.js?:25:3
ReactUpdateQueue.enqueueSetState@webpack:///./~/react/lib/ReactUpdateQueue.js?:210:5
ReactComponent.prototype.setState@webpack:///./~/react/lib/ReactComponent.js?:64:3
handleChange@webpack:///./~/react-redux/lib/components/connect.js?:301:9
dispatch@webpack:///./~/redux/lib/createStore.js?:186:7``

Error is related to the recent change in src/components/Graphs/AbstractGraph.js

domainData.map => domainData.each

**Comment by nxanil** [comment]
@sayaji15 Please review #406
