### ISSUE TITLE
VNF Stats : Sometimes memory graph is not aligned

### ISSUE THREAD

**Issue by urvis** [nuagenetworks/visualization-framework#412]
<img width="1267" alt="memory is not aligned" src="https://user-images.githubusercontent.com/17052729/27496636-b1007b9a-580b-11e7-9d34-c96135edc780.png">
<img width="1266" alt="screen shot 2017-06-22 at 10 38 27 am" src="https://user-images.githubusercontent.com/17052729/27496647-b8113a78-580b-11e7-9ea8-25d8e306138a.png">

**Comment by nxanil** [comment]
@urvis @ronakmshah 

Please review pull request: #417
