### ISSUE TITLE
VNF Stats : Y axis values dont display properly when values equal to 3

### ISSUE THREAD

**Issue by urvis** [nuagenetworks/visualization-framework#415]
duplicate values from 1 to 3 display on Y axis. Values above 3 are displayed correctly, tried it with @ronakmshah on simulator
<img width="1078" alt="screen shot 2017-06-23 at 12 07 26 pm" src="https://user-images.githubusercontent.com/17052729/27496843-94d58bda-580c-11e7-92cd-363740521d94.png">

**Comment by nxanil** [comment]
@urvis @ronakmshah 

Please review pull request: #417
