### ISSUE TITLE
Add a horizontal slider for time at the top of the heatmap

### ISSUE THREAD

**Issue by sayaji15** [nuagenetworks/visualization-framework#419]
User should be able to slide and select intervals of 15 mins. He should be able to go back in time intervals of 15 mins. At a given point of time, he will only see 15 min worth of data

1) when the user comes to the heatmap visualization for the first time, he should see data from "now-15m" to "now". 
2) User can slide the bar to the left and he should be able to see data from "now-30m" to "now-15m"

**Comment by nxanil** [comment]
Seems ok to close.
