### ISSUE TITLE
HeatMap: Application name is not visible and is covered by "Application" on Y axis

### ISSUE THREAD

**Issue by sayaji15** [nuagenetworks/visualization-framework#421]
![image](https://user-images.githubusercontent.com/12192208/27879905-08b7d958-6178-11e7-85ba-fa6872cee86b.png)

**Comment by nxanil** [comment]
@sayaji15 @ronakmshah 
Please review PR #429.

**Comment by sayaji15** [comment]
@nxanil How will this look when the application name is more than 2 characters say 10 characters long ?
Will the fix work ?
