### ISSUE TITLE
VNF : Y axis not aligned correctly for 0.5 value

### ISSUE THREAD

**Issue by urvis** [nuagenetworks/visualization-framework#424]
<img width="1266" alt="y axis 0 5" src="https://user-images.githubusercontent.com/17052729/27970642-722e3cfa-6304-11e7-9196-901c96bb29f4.png">

**Comment by urvis** [comment]
@nxanil pls try verifying with all the 3 time intervals.

**Comment by nxanil** [comment]
Please check the comment of #425 
and let me know whether it will work for you or not.

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
