### ISSUE TITLE
VNF : y axis aligned incorrectly. 0.5 value missing

### ISSUE THREAD

**Issue by urvis** [nuagenetworks/visualization-framework#425]
<img width="1258" alt="y axis 0 5 missing" src="https://user-images.githubusercontent.com/17052729/27970838-291bce82-6305-11e7-8ab4-530696a297d8.png">

**Comment by nxanil** [comment]
@urvis - Please explain the exact issue in this.

**Comment by urvis** [comment]
the x axis has 1.0, 1.5,2.0. similarly there should be 0.5 as well since the increments are 0.5 each.

**Comment by nxanil** [comment]
@urvis 
We have a setting named as "zeroStart" that we can use, if you want to start the graph from "zero".
![image](https://user-images.githubusercontent.com/26645756/28055667-8df29680-6637-11e7-8b68-0e0fe18017e4.png)

After setting it to true Graph will render like:
![image](https://user-images.githubusercontent.com/26645756/28055701-b68c7002-6637-11e7-81fc-9a3ecd1f9fe3.png)

I hope this will resolve this issue.

FYI, without zeroStart option graph will start rendering from minimum value and as result you will not see that (0.5) option.

**Comment by nxanil** [comment]
@ronakmshah 
Verified, ready to close.
