### ISSUE TITLE
npm build is broken due to unmet dependencies on master and 4.0

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#445]
[root@localhost visualization-framework]# npm run build

> visualization-framework@0.0.1 build /home/vagrant/visualization-framework
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Cannot resolve module 'material-ui-datatables' in /home/vagrant/visualization-framework/src/components/Graphs/Table

npm ERR! Linux 3.10.0-514.21.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! visualization-framework@0.0.1 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the visualization-framework@0.0.1 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the visualization-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs visualization-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls visualization-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/visualization-framework/npm-debug.log
[root@localhost visualization-framework]#
[root@localhost visualization-framework]#
[root@localhost visualization-framework]#
[root@localhost visualization-framework]# vi package.json
[root@localhost visualization-framework]#
[root@localhost visualization-framework]#
[root@localhost visualization-framework]# npm install material-ui-datatables
visualization-framework@0.0.1 /home/vagrant/visualization-framework
├─┬ material-ui-datatables@0.18.2
│ ├─┬ babel-runtime@6.25.0
│ │ ├── core-js@2.5.0
│ │ └── regenerator-runtime@0.10.5
│ ├─┬ material-ui@0.18.0
│ │ ├─┬ inline-style-prefixer@3.0.7
│ │ │ └── css-in-js-utils@1.0.3
│ │ ├── lodash.throttle@4.1.1
│ │ ├── UNMET PEER DEPENDENCY react@^15.4.2
│ │ ├── react-event-listener@0.4.5
│ │ └─┬ recompose@0.23.5
│ │   └── symbol-observable@1.0.4
│ ├── UNMET PEER DEPENDENCY react@^15.4.0
│ ├── UNMET PEER DEPENDENCY react-dom@^15.4.0
│ └── UNMET PEER DEPENDENCY react-tap-event-plugin@^2.0.1
├── UNMET PEER DEPENDENCY react@15.3.2
└── UNMET PEER DEPENDENCY react-dom@15.3.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.14 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-addons-transition-group@15.5.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN material-ui-datatables@0.18.2 requires a peer of react@^15.5.4 but none was installed.
npm WARN material-ui-datatables@0.18.2 requires a peer of react-dom@^15.5.4 but none was installed.
npm WARN material-ui@0.18.0 requires a peer of react@^15.4.0 but none was installed.
npm WARN material-ui@0.18.0 requires a peer of react-dom@^15.4.0 but none was installed.
npm WARN material-ui@0.18.0 requires a peer of react-tap-event-plugin@^2.0.1 but none was installed.

Please fix this asap by putting proper dependency.

**Comment by nxanil** [comment]
@ronakmshah 
I have fixed above issue in branch `vss-task-4.0` and merged it into `4.0`.
Do I need to merge this specific commit into master branch?

**Comment by ronakmshah** [comment]
@nxanil yes please
