### ISSUE TITLE
columns overlap in flow detail table

### ISSUE THREAD

**Issue by jinangs** [nuagenetworks/visualization-framework#459]
![overlappingfields](https://user-images.githubusercontent.com/17169726/29642326-0caa2cde-881d-11e7-9dec-c2e44eeda742.jpg)

**Comment by nxanil** [comment]
@jinangs @ronakmshah So would I add the horizontal scrollbar to fix this or break the word to the new line?
Any suggestions?

I'll prefer with the scrollbar.

**Comment by ronakmshah** [comment]
@nxanil for now horizontal bar is safest.

**Comment by nxanil** [comment]
@jinangs 
Please verify this.
