### ISSUE TITLE
Network Performance dashboard doesn't list UBRs 

### ISSUE THREAD

**Issue by varunsachdev** [nuagenetworks/visualization-framework#462]
>> AAR UI: Network Performance dashboard doesn't list UBRs on it's selection based on personality, instead it lists NSGs

>> Due to this UBA-AAR probe stats visualization is blocked

As per Ronak below UI query seems to be wrong

https://10.31.53.110:8443/reports/dashboards/aarNetworkPerformance?aarFlowStatsInterval=30&aarProbeStatsInterval=30&api=https%3A%2F%2F10.31.53.110%3A8443&dPersonality=NSG&dnsg=ovs-1&domainName=ncpeDomain1&domainType=nuage_metadata.domainName&duration=24&enterpriseID=67647165-9855-4679-a78f-a4da44b6ffa9&enterpriseName=test_organization&eshost=https%3A%2F%2F10.31.53.117%3A6200&fromTitlePersonality=NSG-UBR&interval=1h&org=csp&prevStartTime=now-48h&refreshInterval=-1&sPersonality=NSG&snsg=ovs-1&startTime=now-24h&toTitlePersonality=NSG&token=Y3Nwcm9vdDplMDRmNDUwOC01YmMyLTQ2YTQtODkwMS0yMDE4NmZkZjg0MDE%3D&unit=h&vsd-from-nsgs-table-fromPersonality=NSGDUC&vsd-to-nsgs-table-toPersonality=NSG&vsdfromnsgstablefromPersonality=NSG&vsdtonsgstabletoPersonality=NSG

**Comment by ronakmshah** [comment]
@nxanil this is blocker for the release. Please try to work on it asap.

vsdfromnsgstablefromPersonality=NSG is not correct.

it should be fromPersonality only.

visualization-id  = vsd-from-nsgs-table
filterId = fromPersonality

Reference Code:
https://github.com/nuagenetworks/visualization-framework/blob/master/public/configurations/visualizations/vsd-from-nsgs-table.json

I think we have screwed up the context via:
https://github.com/nuagenetworks/visualization-framework/pull/442/files#diff-05f96d644bd5daa4d92af109da26b175

You can use pps-simulator and look at the dashboard aarNetworkPerformance for testing.

**Comment by nxanil** [comment]
@varunsachdev Please verify this.

**Comment by atmahesh** [comment]
@nxanil @ronakmshah Is the fix available in 5.1/latest?

**Comment by atmahesh** [comment]
@nxanil I am able to see list of OVS with personality as UBR now but still see "(undefined)" keyword after OVS. Seems something wrong with query below, please fix this. 

https://10.31.53.110:8443/reports/dashboards/aarNetworkPerformance?aarFlowStatsInterval=30&aarProbeStatsInterval=30&api=https%3A%2F%2F10.31.53.110%3A8443&dPersonality=NSG&dnsg=ovs-1&domainName=ncpeDomain1&domainType=nuage_metadata.domainName&duration=24&enterpriseID=bb2a8d38-8074-43ee-965f-e278f0207853&enterpriseName=test_organization&eshost=https%3A%2F%2F10.31.53.117%3A6200&interval=1h&org=csp&prevStartTime=now-48h&refreshInterval=-1&sPersonality=NSGDUC&snsg=ovs-7&startTime=now-24h&token=Y3Nwcm9vdDpiYTU3YWE0OS04MjA1LTRjOWMtYmNjNS0wMDhkNmUzOTc0Mzc%3D&unit=h&vsdfromnsgstablefromPersonality=NSGDUC&vsdfromnsgstablefromTitlePersonality=NSG-UBR&vsdtonsgstabletoPersonality=NSG&vsdtonsgstabletoTitlePersonality=NSG
cc @ronakmshah @varunsachdev

**Comment by ronakmshah** [comment]
@nxanil seems like context here:
https://github.com/nuagenetworks/visualization-framework/blob/master/public/configurations/visualizations/aar-domain-probe-table.json#L4

is not getting passed to fromPersonality and toPersonality which is shown as undefined

**Comment by nxanil** [comment]
@ronakmshah Please review pull request # 469
