### ISSUE TITLE
sorting based on application doesn't work in flow detail table

### ISSUE THREAD

**Issue by jinangs** [nuagenetworks/visualization-framework#465]
Sorting based on L7 application in Flow detail table doesn't work.

Position of Flow # 3 in attached screenshots doesn't change when flows are sorted by Application.
![l7appsort-1](https://user-images.githubusercontent.com/17169726/29798429-bde6f110-8c11-11e7-9b33-96eafdbe8c98.jpg)
![l7appsort-2](https://user-images.githubusercontent.com/17169726/29798428-bde43c54-8c11-11e7-9e47-f9b614869bac.jpg)

**Comment by jinangs** [comment]
@nxanil likely its broken for service column too which was newly added. I don't have a setup to confirm this but you can check with L4 service QA team.

**Comment by nxanil** [comment]
@jinangs Please verify this.

**Comment by jinangs** [comment]
@nxanil @ronakmshah still doesn't work. Look at the below screen shots. the position of flows classified as yahoo do not change.
![l7sorting-1](https://user-images.githubusercontent.com/17169726/29897851-b72e558e-8d97-11e7-8aaf-a57807d15565.jpg)
![l7sorting-2](https://user-images.githubusercontent.com/17169726/29897852-b8ec39cc-8d97-11e7-9e5b-c31b4b3409e6.jpg)

**Comment by nxanil** [comment]
@jinangs Please review pull request #469. Sorting issues is fixed now.
