### ISSUE TITLE
tab view in domain view is not highlighted

### ISSUE THREAD

**Issue by xzhao025** [nuagenetworks/visualization-framework#468]
when navigate to domain view.
we have four tabs:
traffic, flow , acl, event analytics etc.
currently we have no way to tell where we are

**Comment by xzhao025** [comment]
![download](https://user-images.githubusercontent.com/29493355/29900537-77ebf57e-8da7-11e7-8a5e-989b6367d6b2.jpg)

**Comment by nxanil** [comment]
@jinangs @xzhao025 

Please share the branch you are currently working upon and the URL that you are using.
At my end - I have tested it for every Dashboards and seems like fine to me.

![image](https://user-images.githubusercontent.com/26645756/29910609-2a305e14-8e48-11e7-9658-1f259bdecf7d.png)

**Comment by xzhao025** [comment]
we are using 0.0 current. not sure how it translate to your git branch.

**Comment by nxanil** [comment]
@xzhao025 So how actually you set it up?
