### ISSUE TITLE
enterprise icon is not shown

### ISSUE THREAD

**Issue by xzhao025** [nuagenetworks/visualization-framework#493]
seeing following error in log:
https://mvqa04.mv.nuagenetworks.net:8443/icons/icon-enterprise.png 404 (Not Found)

**Comment by xzhao025** [comment]
this is 5.1 latest

**Comment by xzhao025** [comment]
![visualizations 4](https://user-images.githubusercontent.com/29493355/31516695-4d0b6682-af4e-11e7-9651-a687c1c87e18.png)

**Comment by ronakmshah** [comment]
I believe the problem is at 
https://github.com/nuagenetworks/visualization-framework/blob/1971d304e8013c313a83507fbc79b3950110fa61/src/components/App/MainMenu.js#L221

src is missing the prefix properly as in following:

https://github.com/nuagenetworks/visualization-framework/blob/1971d304e8013c313a83507fbc79b3950110fa61/src/components/App/MainMenu.js#L95

**Comment by nxanil** [comment]
@ronakmshah 
Yes, you are correct!

**Comment by nxanil** [comment]
Please review PR 499

**Comment by xzhao025** [comment]
![vss-ent-icon-1](https://user-images.githubusercontent.com/29493355/31631342-51831a7a-b26e-11e7-87d2-b4163f91e902.JPG)
![vss-ent-icon-2](https://user-images.githubusercontent.com/29493355/31631344-51aa8510-b26e-11e7-903c-6ce82fe1b0bd.JPG)
I can see it on the left pannel, but there is still the same 404 error in the console log

**Comment by xzhao025** [comment]
am I supposed to see it on the enterprise dashboard as well?

**Comment by minimilk** [comment]
Looking at vssui-master-cur-13e32f, Is (2) expected as Xu mentioned above?

1. Icon shows at the top banner
![enterprise-icon](https://user-images.githubusercontent.com/9605878/34023994-abca38da-e0fc-11e7-8668-2315a21bc9b0.png)


2. Enterprise icon is not in front of enterprise name on the panel
![enterprise-icon-in-front-of-enterprise](https://user-images.githubusercontent.com/9605878/34023982-a1f7e2bc-e0fc-11e7-8072-4e757c12ce38.png)

**Comment by nxanil** [comment]
@minimilk 
Added enterprise icon in front of enterprise name on the panel. Please check

**Comment by minimilk** [comment]
Found Enterprise icon.
![enterprise-icon-fix](https://user-images.githubusercontent.com/9605878/35755443-1f2ec700-081c-11e8-8d34-9a41385c9899.png)
