### ISSUE TITLE
when refreshing enterprise dashboard, some of the graphs go missing

### ISSUE THREAD

**Issue by xzhao025** [nuagenetworks/visualization-framework#494]
see console error when refreshing enterprise dashboard
and we are missing graphs

**Comment by xzhao025** [comment]
[consolelog.txt](https://github.com/nuagenetworks/visualization-framework/files/1380557/consolelog.txt)

**Comment by ronakmshah** [comment]
https://github.com/nuagenetworks/visualization-framework/blob/0f7d1f78382ea8fc8d53f3719ee53453dbdc6662/src/components/Graphs/PieGraph/index.js#L131

This might be the issue per consolelog.

**Comment by nxanil** [comment]
@ronakmshah @xzhao025 
Please check PR 499
