### ISSUE TITLE
event analytics under domain dashboard is not showing anything

### ISSUE THREAD

**Issue by xzhao025** [nuagenetworks/visualization-framework#495]
and we see console error
link for location dashboard
https://mvqa04.mv.nuagenetworks.net:8443/reports/dashboards/vssDomainEvent?actionType=ALLOW&api=https%3A%2F%2Fmvqa04.mv.nuagenetworks.net%3A8443&destination=ANY&destination_field=ANY&domainName=Nuage+Domain&domainType=nuage_metadata.domainName&duration=24&enterpriseID=7c08aeac-0271-44cb-b6ee-ed56b001e715&enterpriseName=EXPRESS-mvqa04&eshost=https%3A%2F%2Fmvqa04.mv.nuagenetworks.net%3A6200&flagtype=SYN&interval=1h&org=csp&prevStartTime=now-48h&refreshInterval=-1&source=ANY&source_field=ANY&startTime=now-24h&token=Y3Nwcm9vdDpkOTljNzBmNS02NDk3LTQyYTYtOWRmNS0xNzlkMWNhNzAyN2M%3D&unit=h&vssStatsInterval=30

**Comment by xzhao025** [comment]
[consolelog2.txt](https://github.com/nuagenetworks/visualization-framework/files/1380601/consolelog2.txt)

**Comment by nxanil** [comment]
@ronakmshah @xzhao025 
Please check PR 499
