### ISSUE TITLE
Handling otherOptions in pie-chart

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#496]
Ran into an issue in Pie-chart where I had configured:

            "label": "Others",
            "limit": 85
        },

Even if I have 2 pies, 1 with >85% the the other pie was showing as "others". 
I believe we need to have at least 10 pies to show the 11th one as "others".

**Comment by nxanil** [comment]
@ronakmshah 
Please check PR 499.
