### ISSUE TITLE
horizontal scroll bar doesn't work in `service detail` and `application detail` tables

### ISSUE THREAD

**Issue by jinangs** [nuagenetworks/visualization-framework#502]
Horizontal scroll bar doesn't work in both tables due to which the complete ACL ID cannot be viewed. Screenshot attached.
<img width="960" alt="app_horizontal_bar" src="https://user-images.githubusercontent.com/17169726/31965632-cb65514c-b8bc-11e7-9ee6-be53f15cbb0a.png">
<img width="960" alt="services_horizontal_bar" src="https://user-images.githubusercontent.com/17169726/31965634-cb9bc4b6-b8bc-11e7-96ff-7a2df84668bf.png">

**Comment by xzhao025** [comment]
discussed this with @jinangs actually the scroll bar being not activated is expected because there is no need for scroll. the issue is more a re-sizable window enhancement
1) we have to move till the very end using the vertical scroll bar and then we will see horizontal scroll bar

**Comment by xzhao025** [comment]
screenshot for 2)
![visualizations 7](https://user-images.githubusercontent.com/29493355/32024339-fe0e0b5a-b990-11e7-8a9a-89b8f8c34205.png)

screenshot for 3)
![visualizations 6](https://user-images.githubusercontent.com/29493355/32024310-dd18406e-b990-11e7-8896-cad9486b9166.png)
