### ISSUE TITLE
heat map click does not work 

### ISSUE THREAD

**Issue by varunsachdev** [nuagenetworks/visualization-framework#505]
![heatmap_error](https://user-images.githubusercontent.com/31358636/32465364-21f219d8-c2f8-11e7-8b1e-3820fe40e78c.PNG)
![heatmap_error_2](https://user-images.githubusercontent.com/31358636/32465365-220ac2d0-c2f8-11e7-8e2d-ad0dceb130ef.PNG)

cc @ronakmshah

**Comment by nxanil** [comment]
Issue fixed and commit to branch **bug/heatmap_click_cell**
