### ISSUE TITLE
Ability to put default search in table

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#508]
Anil,
I need a configuration at the visualization level where I can specify a string which becomes the default search value in search bar when the table is loaded. For ex., in the vss flow explorer I want set 'aclId = "DEFAULT"' as a default string. 

This string will be visible when the graph is loaded and that is fine. When someone deletes it it will show everything again with no filter. 

Can you please provide this functionality?

**Comment by nxanil** [comment]
@ronakmshah,

I have added this functionality in `vss-flow-explorer` branch.
To enable this feature, add `searchText` property in a setting. For e.g
searchText: { columnName === columnValue }
