### ISSUE TITLE
[FlowExplorer] Select search result will trigger refresh

### ISSUE THREAD

**Issue by minimilk** [nuagenetworks/visualization-framework#567]
See screen captures for reproduce steps. It seems the error _Expected_ value but "\"" found._ gave some hit.

![step1-to-search](https://user-images.githubusercontent.com/9605878/34546265-85989642-f0a7-11e7-8a8c-e2783bbc42c2.png)

![step2-data-refresh](https://user-images.githubusercontent.com/9605878/34546266-85ade95c-f0a7-11e7-8f40-63b9287ad93e.png)

**Comment by nxanil** [comment]
@minimilk 
Fixed above issue - **"Select search result will trigger refresh"** in branch `bug/retain-search-data`
Please have a look.

**Comment by minimilk** [comment]
Tried PR vssui_PR571_1b4ffc but found uncaught issue:

![vssui_pr571_1b4ffc_issue_567](https://user-images.githubusercontent.com/9605878/35757764-74f73128-0825-11e8-895b-f904be57c960.png)

**Comment by nxanil** [comment]
@minimilk 
Fixed above issue - "found uncaught issue:" in branch bug/retain-search-data
Please have a look.

**Comment by minimilk** [comment]
Tried PR vssui_PR571_88ba70 and no longer see the issue.

![pr571_88ba70_uncaught_after_click_search_result](https://user-images.githubusercontent.com/9605878/36049313-284b369a-0d97-11e8-92a3-9225ad7fe5c2.png)

**Comment by sreddy80** [comment]
@ronakmshah - I see this issue again. After applying the SEARCH condition, when trying to select a particular flow, it triggers a refresh and unable to select a flow. 
Build : 0.0_1316afc

cc: @nxanil
