### ISSUE TITLE
Heatmap Empty bucket handling

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#589]
@nxanil - Currently, an empty time interval in heatmap is shown as undefined block.
![image](https://user-images.githubusercontent.com/15804045/35701975-c42f6adc-0765-11e8-8c16-e98a52df7519.png)
This is quite a nuisance from UI perspective as it serves no purpose. What would be better is, if this empty time interval can be shown in light grey which would mean no data, and instead of occuring on a new row, it either occurs in the same rows, or the time interval is not shown at all. This implementation is totally your choice. I am posting the response from the query here.

`TRACE: 2018-02-01T20:55:07Z
  -> POST https://10.31.234.210:6200/nuage_natt/nuage_doc_type/_search
  {
    "size": 0,
    "sort": [
      {
        "timestamp": {
          "order": "desc"
        }
      }
    ],
    "query": {
      "bool": {
        "must": [
          {
            "range": {
              "timestamp": {
                "gte": "now-15m",
                "lte": "now-0m",
                "format": "epoch_millis"
              }
            }
          }
        ],
        "filter": {
          "bool": {
            "must": [
              {
                "term": {
                  "EnterpriseName": "test_organization"
                }
              },
              {
                "term": {
                  "SourceNSG": "ovs-1"
                }
              },
              {
                "exists": {
                  "field": "ReachabilityStatus"
                }
              }
            ]
          }
        }
      }
    },
    "aggs": {
      "date_histo": {
        "date_histogram": {
          "field": "timestamp",
          "interval": "2m"
        },
        "aggs": {
          "dnsg": {
            "terms": {
              "field": "DestinationNSG"
            },
            "aggs": {
              "ReachabilityStatus": {
                "terms": {
                  "field": "ReachabilityStatus"
                }
              }
            }
          }
        }
      }
    }
  }
  <- 200
  {
    "took": 5,
    "timed_out": false,
    "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
    },
    "hits": {
      "total": 10,
      "max_score": 0,
      "hits": []
    },
    "aggregations": {
      "date_histo": {
        "buckets": [
          {
            "key_as_string": "2018-02-01T20:40:00.000Z",
            "key": 1517517600000,
            "doc_count": 2,
            "dnsg": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "ovs-2",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                },
                {
                  "key": "ovs-3",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            "key_as_string": "2018-02-01T20:42:00.000Z",
            "key": 1517517720000,
            "doc_count": 2,
            "dnsg": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                
              ]
            }
          },
          {
            "key_as_string": "2018-02-01T20:44:00.000Z",
            "key": 1517517840000,
            "doc_count": 2,
            "dnsg": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "ovs-2",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                },
                {
                  "key": "ovs-3",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            "key_as_string": "2018-02-01T20:46:00.000Z",
            "key": 1517517960000,
            "doc_count": 2,
            "dnsg": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "ovs-2",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                },
                {
                  "key": "ovs-3",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            "key_as_string": "2018-02-01T20:48:00.000Z",
            "key": 1517518080000,
            "doc_count": 2,
            "dnsg": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "ovs-2",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                },
                {
                  "key": "ovs-3",
                  "doc_count": 1,
                  "ReachabilityStatus": {
                    "doc_count_error_upper_bound": 0,
                    "sum_other_doc_count": 0,
                    "buckets": [
                      {
                        "key": 0,
                        "doc_count": 1
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    }
  }`

**Comment by bmukheja** [comment]
@nxanil Could you paste a screenshot of how it looks like?

**Comment by nxanil** [comment]
@bmukheja 

Please have a look - 

![f09f1cb99564d54b9f27beb675f919ed](https://user-images.githubusercontent.com/26645756/35911510-ff2b8486-0c1f-11e8-8ef5-6a843bd247dc.png)
