### ISSUE TITLE
Filter on search box having an issue

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#604]
!= 0 is not working.

**Comment by akothap12** [comment]
![image 6](https://user-images.githubusercontent.com/36906330/36765332-813d7e6e-1be5-11e8-8a63-76fb45e17b07.png)
The image to show that the stats are not working for 0

**Comment by nxanil** [comment]
@ronakmshah 
Issue fixed in PR #605.
