### ISSUE TITLE
Table column is not populated on boolean entry

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#616]
If a column mentioned in the table has boolean entry, it displays empty. However, if colors are mapped to that column, it works as expected.
For example - The column named "Flapping" is mapped to elasticsearch field "MultipleStatesChanged"

![image](https://user-images.githubusercontent.com/15804045/37802453-e3e99c14-2e00-11e8-85d4-cc1ba191ac0c.png)

**Comment by nxanil** [comment]
@bmukheja Lets close this ticket now.
