### ISSUE TITLE
Tabifying List inside index entry

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#617]
If an index entry looks like the below where we have a list as a value of an key, the tabification is not being done properly. We need a way to be able to use that particular list as a source of all the columns for a table.

```json
 {
          "TunnelID": "55f0dd47-f94a-455b-94e0-b2127ac57e87",
          "ProbeID": "7d462f38-c579-4c13-84f1-2545105904ec",
          "timestamp": 1521678424467,
          "Tier1State": "UP",
          "ProbeName": "probe-1",
          "SourceNSG": "ovs-1",
          "TunnelName": "My_Ikev2_Gw_Conn_2",
          "Tier2State": "DOWN",
          "ProbeState": "DOWN",
          "MultipleStatesChanged": false,
          "RoundRobinState": "COMPLETE",
          "SrcNSG": "199.169.119.163",
          "Tier1URLInfo": [
            {
              "UrlUUID": "67550077-44f3-4249-add3-ea33b0dfc4e8",
              "UrlString": "http://netflix.com",
              "UrlState": "UP"
            },
            {
              "UrlUUID": "a64a47a4-f55b-4bb0-914e-52a05ee5f21c",
              "UrlString": "http://facebook.com",
              "UrlState": "UP"
            },
            {
              "UrlFailureReason ": "PROBE_RESPONSE_FAILURE",
              "UrlUUID": "e02ad460-f187-48b5-82bb-b8bd8f93f346",
              "UrlString": "http://google.com/text1.html",
              "UrlState": "DOWN"
            },
            {
              "UrlUUID": "acdd76b6-1674-4b19-b143-ec5612474ac9",
              "UrlString": "http://yahoo.com",
              "UrlState": "UP"
            },
            {
              "UrlUUID": "604abdf4-9411-46d2-8615-0c60a4043265",
              "UrlString": "http://nokia.com",
              "UrlState": "UP"
            }
          ],
          "Tier2URLInfo": [
            {
              "UrlFailureReason ": "PROBE_RESPONSE_FAILURE",
              "UrlUUID": "90580113-e740-4bab-8c20-0a1469fc7d1e",
              "UrlString": "http://google.com/text2.html",
              "UrlState": "DOWN"
            },
            {
              "UrlUUID": "49c8a5a6-bce2-4a5c-8157-d425c5bea327",
              "UrlString": "http://nokia.com",
              "UrlState": "UP"
            }
          ]
}
```

For the above entry from elasticsearch, if I want to display a table as below -

| Timestamp | Tier1URLInfo.UrlUUID | Tier1URLInfo.UrlString | Tier1URLInfo.UrlState | Tier1URLInfo.UrlFailureReason | 
| --- | --- | --- | --- | --- |
| 1521678424467 | "67550077-44f3-4249-add3-ea33b0dfc4e8" | "http://netflix.com" | "UP" |  |
| 1521678424467 | "a64a47a4-f55b-4bb0-914e-52a05ee5f21c" | "http://facebook.com" | "UP" |  |
| 1521678424467 | "e02ad460-f187-48b5-82bb-b8bd8f93f346" | "http://google.com/text1.html" | "DOWN" | "PROBE_RESPONSE_FAILURE" |

or as below - 

| Timestamp | Tier2URLInfo.UrlString | Tier2URLInfo.UrlState | Tier2URLInfo.UrlFailureReason | 
| --- | --- | --- | --- |
| 1521678424467 | "http://nokia.com" | "UP" |  |
| 1521678424467 |  "http://google.com/text2.html" | "DOWN" | "PROBE_RESPONSE_FAILURE" |

I should be able to. 

The number of entries inside Tier1UrlInfo or Tier2UrlInfo is not fixed. Hence, the tabification should produce a uniform table from which entries can be taken to visualise. 

There is no need to merge the data from Tier1UrlInfo or Tier2UrlInfo, it can be kept separate, where if one field is present, other is empty.

Kindly let me know if any questions

**Comment by bmukheja** [comment]
@nxanil Can you provide an ETA for this? This is kind of high priority now.

**Comment by nxanil** [comment]
@bmukheja Do you have some elasticsearch query, so that I can use that to work on something like this.

**Comment by nxanil** [comment]
@bmukheja Could you please let me know about the elasticsearch query which I need to use, to work over tabify?

**Comment by bmukheja** [comment]
@nxanil The query is just to return the full index, from which we create the table. From that table, I can choose to then display columns, so essentially, query would be like this -

```json
{
    "id": "aar-nsg-ike-probe-tier1-detail-table",
    "title": "IKE Tier1 URL state table",
    "service": "elasticsearch",
    "query": {
        "index": "{{index:nuage_ike_probestats}}",
        "type": "{{type:nuage_doc_type}}",
        "body": {
            "size": "1",
            "sort": [
                {
                    "timestamp": {
                        "order": "desc"
                    }
                }
            ],
            "query": {
                "bool": {
                    "filter": {
                        "bool": {
                            "must": [
                                {
                                    "range": {
                                        "timestamp": {
                                            "lte": "{{ikeProbeDetailTimestamp}}",
                                            "gte": "{{ikeProbeDetailTimestamp}}",
                                            "format": "epoch_millis"
                                        }
                                    }
                                },
                                {
                                    "term": {
                                        "SourceNSG": "{{snsg}}"
                                    }
                                },
                                {
                                    "term": {
                                        "TunnelName": "{{tunnel}}"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    }
}
```
We can't do an elasticsearch aggregation here as elasticsearch doesn't do aggregated of multilevel fields very well.

So, the response we expect would look something like this - 

```json
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 10,
    "successful" : 10,
    "failed" : 0
  },
  "hits" : {
    "total" : 1990,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "nuage_ike_probestats-2018-03-26",
        "_type" : "nuage_doc_type",
        "_id" : "AWJg-4MPOXL3gbktbvc9",
        "_score" : 1.0,
        "_source" : {
          "Tier2State" : "STOPPED",
          "ProbeState" : "DOWN",
          "MultipleStatesChanged" : false,
          "SrcNSG" : "118.38.109.59",
          "Tier1URLInfo": [
            {
              "UrlUUID": "67550077-44f3-4249-add3-ea33b0dfc4e8",
              "UrlString": "http://netflix.com",
              "UrlState": "UP"
            },
            {
              "UrlUUID": "a64a47a4-f55b-4bb0-914e-52a05ee5f21c",
              "UrlString": "http://facebook.com",
              "UrlState": "UP"
            },
            {
              "UrlFailureReason ": "PROBE_RESPONSE_FAILURE",
              "UrlUUID": "e02ad460-f187-48b5-82bb-b8bd8f93f346",
              "UrlString": "http://google.com/text1.html",
              "UrlState": "DOWN"
            },
            {
              "UrlUUID": "acdd76b6-1674-4b19-b143-ec5612474ac9",
              "UrlString": "http://yahoo.com",
              "UrlState": "UP"
            },
            {
              "UrlUUID": "604abdf4-9411-46d2-8615-0c60a4043265",
              "UrlString": "http://nokia.com",
              "UrlState": "UP"
            }
          ],
          "Tier2URLInfo": [
            {
              "UrlFailureReason ": "PROBE_RESPONSE_FAILURE",
              "UrlUUID": "90580113-e740-4bab-8c20-0a1469fc7d1e",
              "UrlString": "http://google.com/text2.html",
              "UrlState": "DOWN"
            },
            {
              "UrlUUID": "49c8a5a6-bce2-4a5c-8157-d425c5bea327",
              "UrlString": "http://nokia.com",
              "UrlState": "UP"
            }
          ],
          "TunnelID" : "61ad58c5-ae6d-494b-b9c2-3e9548b9e881",
          "ProbeFailureReason" : "TIER_1",
          "ProbeID" : "10b01628-b4d4-4607-a586-8552b772fb14",
          "timestamp" : 1522045515019,
          "Tier1State" : "DOWN",
          "ProbeName" : "probe-1",
          "SourceNSG" : "ovs-1",
          "TunnelName" : "My_Ikev2_Gw_Conn_4"
        }
      },
      {
        "_index" : "nuage_ike_probestats-2018-03-26",
        "_type" : "nuage_doc_type",
        "_id" : "AWJhIBcxOXL3gbktbwfB",
        "_score" : 1.0,
        "_source" : {
          "Tier2State" : "STOPPED",
          "ProbeState" : "DOWN",
          "MultipleStatesChanged" : false,
          "SrcNSG" : "118.38.109.59",
          "Tier1URLInfo": [
            {
              "UrlUUID": "67550077-44f3-4249-add3-ea33b0dfc4e8",
              "UrlString": "http://netflix.com",
              "UrlState": "UP"
            },
            {
              "UrlUUID": "a64a47a4-f55b-4bb0-914e-52a05ee5f21c",
              "UrlString": "http://facebook.com",
              "UrlState": "UP"
            },
            {
              "UrlFailureReason ": "PROBE_RESPONSE_FAILURE",
              "UrlUUID": "e02ad460-f187-48b5-82bb-b8bd8f93f346",
              "UrlString": "http://google.com/text1.html",
              "UrlState": "DOWN"
            },
            {
              "UrlUUID": "acdd76b6-1674-4b19-b143-ec5612474ac9",
              "UrlString": "http://yahoo.com",
              "UrlState": "UP"
            },
            {
              "UrlUUID": "604abdf4-9411-46d2-8615-0c60a4043265",
              "UrlString": "http://nokia.com",
              "UrlState": "UP"
            }
          ],
          "Tier2URLInfo": [
            {
              "UrlFailureReason ": "PROBE_RESPONSE_FAILURE",
              "UrlUUID": "90580113-e740-4bab-8c20-0a1469fc7d1e",
              "UrlString": "http://google.com/text2.html",
              "UrlState": "DOWN"
            },
            {
              "UrlUUID": "49c8a5a6-bce2-4a5c-8157-d425c5bea327",
              "UrlString": "http://nokia.com",
              "UrlState": "UP"
            }
          ],
          "TunnelID" : "13f36843-6171-45e1-bec3-5f72aec0bb00",
          "ProbeFailureReason" : "TIER_1",
          "ProbeID" : "10b01628-b4d4-4607-a586-8552b772fb14",
          "timestamp" : 1522047913842,
          "Tier1State" : "DOWN",
          "ProbeName" : "probe-1",
          "SourceNSG" : "ovs-1",
          "TunnelName" : "My_Ikev2_Gw_Conn_2"
        }
      }
    ]
  }
}
```


Since I want only to have it tabified, the tabified version I believe would look something like this -

| _index | _type | _id | _score | timestamp | ProbeName | TunnelName | SourceNSG | ProbeID | ProbeFailureReason | TunnelID | ProbeState | SrcNSG | MultipleStatesChanged | Tier1State | Tier2State | Tier1URLInfo.UrlUUID | Tier1URLInfo.UrlString | Tier1URLInfo.UrlState | Tier1URLInfo.UrlFailureReason | Tier2URLInfo.UrlUUID | Tier2URLInfo.UrlString | Tier2URLInfo.UrlState | Tier2URLInfo.UrlFailureReason | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJg-4MPOXL3gbktbvc9" | 1.0 | 1522045515019 | "probe-1" | "My_Ikev2_Gw_Conn_4" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "61ad58c5-ae6d-494b-b9c2-3e9548b9e881" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "67550077-44f3-4249-add3-ea33b0dfc4e8" | http://netflix.com | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJg-4MPOXL3gbktbvc9" | 1.0 | 1522045515019 | "probe-1" | "My_Ikev2_Gw_Conn_4" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "61ad58c5-ae6d-494b-b9c2-3e9548b9e881" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "a64a47a4-f55b-4bb0-914e-52a05ee5f21c" | http://facebook.com | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJg-4MPOXL3gbktbvc9" | 1.0 | 1522045515019 | "probe-1" | "My_Ikev2_Gw_Conn_4" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "61ad58c5-ae6d-494b-b9c2-3e9548b9e881" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "e02ad460-f187-48b5-82bb-b8bd8f93f346" | http://google.com/text1.html | "DOWN" | "PROBE_RESPONSE_FAILURE" |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJg-4MPOXL3gbktbvc9" | 1.0 | 1522045515019 | "probe-1" | "My_Ikev2_Gw_Conn_4" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "61ad58c5-ae6d-494b-b9c2-3e9548b9e881" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "acdd76b6-1674-4b19-b143-ec5612474ac9" | http://yahoo.com | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJg-4MPOXL3gbktbvc9" | 1.0 | 1522045515019 | "probe-1" | "My_Ikev2_Gw_Conn_4" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "61ad58c5-ae6d-494b-b9c2-3e9548b9e881" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "604abdf4-9411-46d2-8615-0c60a4043265" | http://nokia.com" | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJg-4MPOXL3gbktbvc9" | 1.0 | 1522045515019 | "probe-1" | "My_Ikev2_Gw_Conn_4" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "61ad58c5-ae6d-494b-b9c2-3e9548b9e881" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "604abdf4-9411-46d2-8615-0c60a4043265" |  |  |  | "90580113-e740-4bab-8c20-0a1469fc7d1e" | http://google.com/text2.html | "DOWN" | "PROBE_RESPONSE_FAILURE"
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJg-4MPOXL3gbktbvc9" | 1.0 | 1522045515019 | "probe-1" | "My_Ikev2_Gw_Conn_4" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "61ad58c5-ae6d-494b-b9c2-3e9548b9e881" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "604abdf4-9411-46d2-8615-0c60a4043265" |  |  |  | "49c8a5a6-bce2-4a5c-8157-d425c5bea327" | http://nokia.com | "UP" | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJhIBcxOXL3gbktbwfB" | 1.0 | 1522047913842 | "probe-1" | "My_Ikev2_Gw_Conn_2" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "13f36843-6171-45e1-bec3-5f72aec0bb00" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "67550077-44f3-4249-add3-ea33b0dfc4e8" | http://netflix.com | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJhIBcxOXL3gbktbwfB" | 1.0 | 1522047913842 | "probe-1" | "My_Ikev2_Gw_Conn_2" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "13f36843-6171-45e1-bec3-5f72aec0bb00" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "a64a47a4-f55b-4bb0-914e-52a05ee5f21c" | http://facebook.com | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJhIBcxOXL3gbktbwfB" | 1.0 | 1522047913842 | "probe-1" | "My_Ikev2_Gw_Conn_2" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "13f36843-6171-45e1-bec3-5f72aec0bb00" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "e02ad460-f187-48b5-82bb-b8bd8f93f346" | http://google.com/text1.html | "DOWN" | "PROBE_RESPONSE_FAILURE" |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJhIBcxOXL3gbktbwfB" | 1.0 | 1522047913842 | "probe-1" | "My_Ikev2_Gw_Conn_2" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "13f36843-6171-45e1-bec3-5f72aec0bb00" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "acdd76b6-1674-4b19-b143-ec5612474ac9" | http://yahoo.com | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJhIBcxOXL3gbktbwfB" | 1.0 | 1522047913842 | "probe-1" | "My_Ikev2_Gw_Conn_2" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "13f36843-6171-45e1-bec3-5f72aec0bb00" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "604abdf4-9411-46d2-8615-0c60a4043265" | http://nokia.com" | "UP" |  |  |  |  | 
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJhIBcxOXL3gbktbwfB" | 1.0 | 1522047913842 | "probe-1" | "My_Ikev2_Gw_Conn_2" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "13f36843-6171-45e1-bec3-5f72aec0bb00" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "604abdf4-9411-46d2-8615-0c60a4043265" |  |  |  | "90580113-e740-4bab-8c20-0a1469fc7d1e" | http://google.com/text2.html | "DOWN" | "PROBE_RESPONSE_FAILURE"
| "nuage_ike_probestats-2018-03-26" | "nuage_doc_type" | "AWJhIBcxOXL3gbktbwfB" | 1.0 | 1522047913842 | "probe-1" | "My_Ikev2_Gw_Conn_2" | "ovs-1" | "10b01628-b4d4-4607-a586-8552b772fb14" | "TIER_1" | "13f36843-6171-45e1-bec3-5f72aec0bb00" | "DOWN" | "118.38.109.59" | FALSE | "DOWN" | "STOPPED" | "604abdf4-9411-46d2-8615-0c60a4043265" |  |  |  | "49c8a5a6-bce2-4a5c-8157-d425c5bea327" | http://nokia.com | "UP" | 


You can choose to fill "N/A" in place of empty cell, but this is what I envision would be the simplest and most useful for future use.

Please spend some time to understand the conversion as its a little complex, but it should be straight forward once you get the hang of it. Let me know if there are any questions, and we can discuss over the call as well.

**Comment by bmukheja** [comment]
Good Job @nxanil . Exactly what we needed. While applying this, I also figured we would need a way to eliminate blank rows from a table, if they are all blank. Could you please make that as a change in the same PR? Provide an option to the user to "eliminateBlankRows" which is set to true by default.

**Comment by nxanil** [comment]
@bmukheja Please let me know if you need anything else, or let us close this ticket now.

**Comment by bmukheja** [comment]
Works good! Thanks @nxanil
