### ISSUE TITLE
Cannot filter flows based on Type in FlowExplorer

### ISSUE THREAD

**Issue by anuragj** [nuagenetworks/visualization-framework#630]
In latest Visualization framework build, not able to filter flows based on Type field.  I have several flows with type as DENY but when I filter using Type == DENY, no flows are returned.
![flow-expl-1](https://user-images.githubusercontent.com/11930833/38390426-24bf8944-38d6-11e8-83da-92d973ddf516.JPG)
![flow-expl-2](https://user-images.githubusercontent.com/11930833/38390433-286c2aca-38d6-11e8-9c3a-82a37c6de5e8.JPG)

**Comment by nxanil** [comment]
@anuragj @ronakmshah 
Fixed and make PR #633
