### ISSUE TITLE
Select Columns field font needs a reduction

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#632]
Select Columns is appearing larger than other fonts on the dashboard. Can you please rectify and make it uniform with other fonts. Thanks.

![screen shot 2018-04-05 at 2 48 32 pm](https://user-images.githubusercontent.com/1153786/38393698-7f3fad72-38e0-11e8-9ba2-36869f374a53.png)

**Comment by nxanil** [comment]
@ronakmshah 

Fixed and make PR #634

**Comment by nxanil** [comment]
@ronakmshah @bmukheja 

Add some styling to make the search bar more visible. Please have a look and let me know.
Note: There is no option to add the placeholder in `react-filter-box` library. So I have added label instead of the placeholder.
