### ISSUE TITLE
Styling in 'i' tab

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#640]
Right now all text is aligned left, without support for newline or tab. It could be discussed what kind of styling is needed there, and then arrived at a design choice, so I am opening this for discussion. cc @ronakmshah @nxanil

**Comment by nxanil** [comment]
@ronakmshah @bmukheja 

I have made some design changes for ' i ' tab description as of it now.

Now talk about UI/UX of the project, as we know we have not worked explicitly on UI/UX part of the project and there are tons of things need to improve in UI/UX parts of the project. So I need to discuss some basics things related to design from our UI/UX team. We have already proposed a design to Natalia for another project from your side. Below are some sample pages of UI:-
[Nokia.zip](https://github.com/nuagenetworks/visualization-framework/files/1907581/Nokia.zip)

I would like to suggest that we can re-design the project with the help our UI/UX team or we can work on to improve basic design. Your thought, please?

**Comment by bmukheja** [comment]
@nxanil - Regarding the UI/UX aspect, can you present the sample pages with a little walkthrough in our meeting, the meeting platform is better to discuss a change of this kind. Thanks.
