### ISSUE TITLE
FlowExplorer fails to load for certain output

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#642]
The problem is with vssFlowExplorer dashboard. I believe there is a specific type column in response which is not handled properly.

![img1](https://user-images.githubusercontent.com/1153786/38702682-18e1f0be-3e56-11e8-8cb6-b7f3483d2fbe.png)
![img2](https://user-images.githubusercontent.com/1153786/38702688-1a906bf2-3e56-11e8-9a13-58ecae14a68f.png)

**Comment by nxanil** [comment]
@ronakmshah 
Fixed in PR #643
