### ISSUE TITLE
Secondary query in Geomap

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#652]
Currently, if the elasticsearch query in a geomap doesn't return any result, the graph shows "No data to display" even if there is location data present from the VSD query. Instead, what is required is that the location markers keep displayed, but the links data from Elasticsearch is overlayed above that, so in case a node doesn't have any link to the other, the node is still displayed.

**Comment by nxanil** [comment]
@bmukheja 

I have removed the check. Please have a look

**Comment by bmukheja** [comment]
@nxanil - Hope the primary query is still necessary, as in we don't want to show links from nodes which are absent.

**Comment by nxanil** [comment]
@bmukheja 
Yes. The primary query is necessary.

**Comment by bmukheja** [comment]
@nxanil - This is not working, it is still giving "Unable to fetch data" when the ES query fails, but in this case there is no index for the link data as well. Hence query is not running on ES.

This is the query - 
```
 {
    "size": 0,
    "query": {
      "bool": {
        "must": [
          {
            "range": {
              "timestamp": {
                "gte": "now-24h",
                "lte": "now",
                "format": "epoch_millis"
              }
            }
          }
        ]
      }
    },
    "aggs": {
      "source": {
        "terms": {
          "field": "SourceNSG"
        },
        "aggs": {
          "destination": {
            "terms": {
              "field": "DestinationNSG"
            }
          }
        }
      }
    }
  }
  <- 404
  {
    "error": {
      "root_cause": [
        {
          "type": "index_not_found_exception",
          "reason": "no such index",
          "resource.type": "index_or_alias",
          "resource.id": "nuage_dpi_flowstats",
          "index_uuid": "_na_",
          "index": "nuage_dpi_flowstats"
        }
      ],
      "type": "index_not_found_exception",
      "reason": "no such index",
      "resource.type": "index_or_alias",
      "resource.id": "nuage_dpi_flowstats",
      "index_uuid": "_na_",
      "index": "nuage_dpi_flowstats"
    },
    "status": 404
  }
```

**Comment by nxanil** [comment]
@bmukheja,

Seems working fine at my end, are you testing it in `feature/geomap ` ?

**Comment by nxanil** [comment]
@bmukheja 

I have added an option to make secondary queries as optional queries and make PR
By default, all the queries are mandatory, and if you want to make any query as an optional query then explicitly set flag `required: false` as given below: 


             `"query": {
                       "data": "vnf-status-linechart",
                        "data2": {"name": "vnf-status", "required": false}
             }`
Note: data query always remain mandatory.

Please merge above PR to your geomap branch and set the flag `required: false` to make ES query optional. Please have a look.
