### ISSUE TITLE
Geomap UI gets messy on zoom out

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#670]
Upon unzoom the Geo Maps UI looks messed up and shows multiple duplicates of the globe Map.
Screenshot attached

![unzoom](https://user-images.githubusercontent.com/15804045/39776947-388cab46-52d0-11e8-8d56-3491705814de.PNG)

**Comment by nxanil** [comment]
@bmukheja 
Fixed in commit f309360f5c98982ffe110b9822203eb8b6638c8f
