### ISSUE TITLE
Time (X-Axis) in ICMP vs Time Graph and UDP vs Time is not displaying correctly

### ISSUE THREAD

**Issue by anuragj** [nuagenetworks/visualization-framework#678]
The X-Axis in ICMP vs Time graph in VSS UI seems to be broken. For last 24 hour graph, X-Axis shows no time. For last 15 mins, its showing time as string,

![image](https://user-images.githubusercontent.com/11930833/40443859-7043170c-5e7c-11e8-9a1f-a29e73e0339a.png)

![image](https://user-images.githubusercontent.com/11930833/40443906-9a0986a2-5e7c-11e8-9ed6-1663841865f6.png)

For UDP vs time , time axis is always empty:
![image](https://user-images.githubusercontent.com/11930833/40443933-b07e2fe6-5e7c-11e8-9627-5ca2bbad1144.png)

**Comment by nxanil** [comment]
@anuragj 
Fixed in PR #681.

**Comment by anuragj** [comment]
Hi @nxanil   , Can you please merge the change. I can just verify in master build. I can reopen if anymore changes are required.
