### ISSUE TITLE
Stack exception on  Flow Analytics on changing Group By

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/visualization-framework#684]
See attached screenshots:

![action_deny](https://user-images.githubusercontent.com/4873481/41937264-b3d48068-7944-11e8-88d2-bcc7e80e42e0.PNG)
![flowsperdomain_error](https://user-images.githubusercontent.com/4873481/41937265-b3eaa852-7944-11e8-87fb-767fba5ece2e.PNG)

**Comment by nxanil** [comment]
@natabal 

Please let me know the branch name where stack exceptions are coming. Thanks

**Comment by nxanil** [comment]
@natabal: Ok, sure and when does this build is created from the master branch. Just want to make sure, we are working on the latest codebase, as it seems like there are respective checks already there in the master branch. I am still looking at it further.

**Comment by natabal** [comment]
@nxanil This was built on Jun 18th if you fill that some changes made since has fixed this I can ask the QA to load the latest build on the testbed

**Comment by natabal** [comment]
@sreddy80 Can you please add the steps to reproduce

**Comment by sreddy80** [comment]
@nxanil - Please follow below steps to reproduce the issue:

1. Set ACL Action to 'Deny' on Top Source IP by # packets chart 
![image](https://user-images.githubusercontent.com/35505013/41996884-22e2014e-7a0b-11e8-920f-fa8e97ff51b1.png)

2. switch Group By value on Flows per Domain chart 
![image](https://user-images.githubusercontent.com/35505013/41996916-34e58410-7a0b-11e8-8ff8-aaabbb620531.png)

**Comment by nxanil** [comment]
@natabal Could you please ask them to create the latest build with SUB MODULE of graphs. I have tested it on the latest build and everything seems ok to me.
Please find below latest build created from the master branch and it seems to work fine for me
[build.zip](https://github.com/nuagenetworks/visualization-framework/files/2148976/build.zip)

**Comment by sreddy80** [comment]
@nxanil - I had verified with the latest build 0.0_2666 and was able to reproduce the issue. 

![image](https://user-images.githubusercontent.com/35505013/42117455-6dd670c0-7bb1-11e8-97c5-104e04587b61.png)

cc: @natabal

**Comment by nxanil** [comment]
@sreddy80 It seems like an issue over there, a request, kindly provide me the zip of the build, so that I can dig into the issue.

**Comment by nxanil** [comment]
Fixed https://github.com/nuagenetworks/vis-graphs/pull/4
