### ISSUE TITLE
Virtual Firewall - openContext exception

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/visualization-framework#686]
With the latest changes in the visualization framework, select and right click on a flow throws an exception:

<img width="1414" alt="screen shot 2018-07-09 at 7 09 13 am" src="https://user-images.githubusercontent.com/4873481/42455499-47f2b83a-8347-11e8-9e62-d0347b7456db.png">

**Comment by nxanil** [comment]
Fixed https://github.com/nuagenetworks/vis-graphs/pull/3
