### ISSUE TITLE
Alarms Summary dashboard page ramains on "please wait while loading" state when there are no alarms generated.

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#699]
@nxanil - In this case, the VSD reply is an empty list with status = '200 OK'. The visualization expects a response hence it stays on loading. But in case of empty response from VSD, it should say "No Data to display" just like it does in case of empty elasticsearch response

![image](https://user-images.githubusercontent.com/15804045/42913312-254f6a08-8aa9-11e8-8354-248967b9ec39.png)

API call and its response -

[bmukheja@localhost visualization-framework]$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Nuage-Organization: csp" -H "authorization: XREST Y3Nwcm9vdDpmMzJlNTJmYy01NzgzLTQ4ZWYtYTBkNS00ODRhZmU1ZWU1NmY=" -k https://mvdcvtb36.mv.nuagenetworks.net:8443/nuage/api/v5_0/nsgateways/a9ec0a8e-8ab7-4635-a0bf-a7c3240060b0/alarms
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Pragma: No-cache
Cache-Control: no-cache
Expires: Wed, 31 Dec 1969 16:00:00 PST
Set-Cookie: rememberMe=deleteMe; Path=/nuage; Max-Age=0; Expires=Tue, 17-Jul-2018 23:42:43 GMT
Access-Control-Allow-Origin: *
X-Nuage-OrderBy: timestamp DESC
X-Nuage-Count: 0
Access-Control-Expose-Headers: X-Nuage-Organization, X-Nuage-ProxyUser, X-Nuage-OrderBy, X-Nuage-FilterType, X-Nuage-Filter, X-Nuage-Page, X-Nuage-PageSize, X-Nuage-Count, X-Nuage-Custom, X-Nuage-ClientType, X-SSL-Client-CN, X-SSL-Client-ORG, X-SSL-Client-UID, X-SSL-Issuer-CN, X-SSL-Client-DN, X-SSL-Issuer-DN
Content-Length: 0
Date: Wed, 18 Jul 2018 23:42:43 GMT

[bmukheja@localhost visualization-framework]$

**Comment by nxanil** [comment]
Fixed in PR #702
