### ISSUE TITLE
FilterOptions functionality having bugs

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#701]
@nxanil - If you see the file https://github.com/nuagenetworks/visualization-framework/blob/master/public/configurations/visualizations/aar-nsg-ike-tunnel-traffic-linechart.json

you can see filterOptions and forceOptions specified, but when we run the app, the variables are not being pushed to the context.

This is the context I am getting - 

http://localhost:3000/dashboards/aarNSGIKE?aarFlowStatsInterval=30&aarProbeStatsInterval=30&aarnsgiketunnelheatmapstartTime=now-15m&api=https%3A%2F%2Fmvdcvtb36.mv.nuagenetworks.net%3A8443&dnsg=ovs-1&duration=15&enterpriseID=e4fdfe5c-5f4e-48cd-8c1b-5f4f736d5e1e&enterpriseName=test_organization&eshost=https%3A%2F%2Fmvdcvtb36.mv.nuagenetworks.net%3A6200&interval=2m&metric=TotalBytesCount&nsgId=6d3478d4-1730-4adf-9a7c-d6e5d093a894&org=csp&prevStartTime=now-30m&refreshInterval=-1&snsg=ovs-1&startTime=now-15m&token=Y3Nwcm9vdDphZWYzMDZhYS04NGZiLTRiNjktYWE4MC02YTRhMjgzZDc1NWQ%3D&unit=m

**Comment by bmukheja** [comment]
@nxanil - I have seen forceOptions functionality being broken everywhere, maybe a recent change did that. Kindly check it by your side.

cc: @natabal @ronakmshah

**Comment by nxanil** [comment]
@bmukheja - I tried it in my end, and it seems working fine for me
- What exactly are you doing? 
- Is there any console errors?
- What is the branch you are using? If not master, then do let us know.
- Also, please do confirm,  have you done "npm install" before testing this, just for safer side

I started with:
http://localhost:3000/dashboards/aarNSGIKE

and ends with:
http://localhost:3000/dashboards/aarNSGIKE?aarnsgiketunnelheatmapstartTime=now-15m&duration=15&ikeTrafficColumn=TxBytesCount&ikeTrafficLabel=Bytes&ikeTrafficType=TxBytes&interval=2m&prevStartTime=now-30m&refreshInterval=-1&startTime=now-15m&unit=m

and then changed the drop down to "Rx packets" and ends with:
http://localhost:3000/dashboards/aarNSGIKE?aarnsgiketunnelheatmapstartTime=now-15m&duration=15&ikeTrafficColumn=RxPacketsCount&ikeTrafficLabel=Packets&ikeTrafficType=RxPackets&interval=2m&prevStartTime=now-30m&refreshInterval=-1&startTime=now-15m&unit=m

cc:  @ronakmshah @natabal

**Comment by natabal** [comment]
@nxanil It seems that filterOptions is not populated in mapsToProps for all the visualizations of a dashboard. Have a look at the one mentioned by @bmukheja above. There are no errors in the console but I noticed that the ES query for this visualization is not invoked! Please check this ASAP

**Comment by nxanil** [comment]
@bmukheja @natabal It is working fine at my end, for above as well as other dashboards, and firing the query as well.
Also please note, we cache the result for the same query for around 30 seconds i.e.
Say current drop-down is "A", and when you change it to "B", then the query will get triggered, but if you change it back to "A" within cache time, then we will not fire the query again.

**Comment by bmukheja** [comment]
The key "forceOptionsOverride" instead of "forceOptions". Closing this for now.
