### ISSUE TITLE
Flow explorer showing lesser records than actually present in ES node

### ISSUE THREAD

**Issue by anuragj** [nuagenetworks/visualization-framework#704]
This is in regards to the recent enhancement of Flow Explorer where flow explorer would not show just 1000 records but will shows all the records that are present in ES node for the selected time frame.

In my flow explorer for a given enterprise (Ent-1 ) and domain (e1-l3-Dom-1) for last 24 hours flow explorer shows around 7K entries.

`{
  "size": 1000,
  "sort": [
    {
      "timestamp": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "nuage_metadata.enterpriseName": "Ent-1"
          }
        },
        {
          "term": {
            "nuage_metadata.domainName": "e1-l3-Dom-1"
          }
        },
        {
          "range": {
            "timestamp": {
              "gte": "now-24h",
              "lte": "now",
              "format": "epoch_millis"
            }
          }
        }
      ]
    }
  }
}`

But when I query ES node for this enterprise and domain for last 24 hours, I get 382K results.

`{"query":{"bool":{"must":[{"term":{"nuage_metadata.domainName":"e1-l3-Dom-1"}},{"range":{"timestamp":{"gt":"now-24h","lt":"now"}}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"aggs":{}}`

`Searched 5 of 5 shards. 382569 hits. 0.016 seconds`

![image](https://user-images.githubusercontent.com/11930833/43100410-1c4870c4-8e7a-11e8-81ef-cc99f41d9b06.png)

**Comment by anuragj** [comment]
Also this number keeps on changing. I saw it increase to 7K but it then decreased to 6K again.

**Comment by nxanil** [comment]
@anuragj In the second query `{ "nuage_metadata.enterpriseName": "Ent-1" }` is missing.

Could you please check it again?

Also I believe the number will change as data comes and goes from the 15 minutes window frame.

**Comment by anuragj** [comment]
@nxanil  Its not required for me to give enterprise name as Ent-1. I only have one enterprise and also my domain names are unique.  So domain name e1-l3-Dom-1  means it belongs to Ent-1. 

I had traffic running for 1 hour and my filter was set to last 24hrs. The number was changing but it was not going beyond 7k

cc : @ronakmshah

**Comment by ronakmshah** [comment]
@nxanil this is a blocker. @anuragj  is seeing an issue where the number of flows are decreasing in some cases dynamically. Can you please take a look at the logic and make sure that we are doing scrolling the way it should. You can use simulator to pump in lot more data, change the query such that you get smaller chunk at the time to reproduce the issue if need be.

**Comment by nxanil** [comment]
@ronakmshah Yes, I am working on this item as a top priority.

**Comment by nxanil** [comment]
@ronakmshah Fixed and merged branch in master.
