### ISSUE TITLE
scroll is enabled for all the ES queries by default

### ISSUE THREAD

**Issue by ronakmshah** [nuagenetworks/visualization-framework#705]
I see that all the queries in ES across different VSS dashboard have scroll enabled. Thats neither a design nor requirement. Please fix this.

**Comment by nxanil** [comment]
@ronakmshah 
Fixed in commit  https://github.com/nuagenetworks/visualization-framework/pull/683/commits/9bba0e0b51dd874ff8a5392ee2d59f056fdd2f88 . Please have a look
