### ISSUE TITLE
Another set of graphs missing

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#709]
@natabal - The graphs on this dashboard are missing. As discussed, please have a look at them.

Please find the setup on - https://mvdcvtb36.mv.nuagenetworks.net:8443

You can use the following link for the dashboard

https://mvdcvtb36.mv.nuagenetworks.net:8443/reports/dashboards/aarNSGDetail?IpType=SrcIp&NsgType=SourceNSG&aarFlowStatsInterval=30&aarProbeStatsInterval=30&api=https%3A%2F%2Fmvdcvtb36.mv.nuagenetworks.net%3A8443&bytesType=IngressBytes&dnsg=ovs-1&duration=24&enterpriseID=8a76331f-4e40-45d1-bf43-68931f5e56bb&enterpriseName=test_organization&eshost=https%3A%2F%2Fmvdcvtb36.mv.nuagenetworks.net%3A6200&interval=1h&metric=TotalBytesCount&nsgId=ec3be591-aaba-4349-a03e-413cdc091e1d&org=csp&prevStartTime=now-48h&refreshInterval=-1&snsg=ovs-1&startTime=now-24h&token=Y3Nwcm9vdDo0OTM0NDJmMC04ZTZlLTQ0N2EtYTJjOC04NmM3Mjk0OGY5MDA%3D&trafficType=Upload&unit=h&zeroBytesType=EgressBytes

**Comment by natabal** [comment]
@bmukheja This is a configuration issue as mentioned in the jira ticket! the 'nsg' parameter required by the 3 visualization queries is not available in the context

**Comment by natabal** [comment]
@bmukheja is this fixed?
