### ISSUE TITLE
Heatmap Visualization scroll not working for ike_stats (JIRA bug VRS-15965)

### ISSUE THREAD

**Issue by psjawale** [nuagenetworks/visualization-framework#720]
The latest page on ike_stats tab displays information correctly (refer heatmap-1)
![heatmap-1](https://user-images.githubusercontent.com/15370884/44291000-7c292000-a230-11e8-8b54-65f567525103.PNG)

When we scroll to the previous page to see history, it displays no data available (refer heatmap-2)
![heatmap-2](https://user-images.githubusercontent.com/15370884/44291008-83e8c480-a230-11e8-83be-daca2f69d10a.PNG)

The old history is available on elastic search.
On the latest page when we select time interval as 60mins, we see all the information as expected (refer heatmap-3)

![heatmap-3](https://user-images.githubusercontent.com/15370884/44291012-864b1e80-a230-11e8-867a-56977a5bd532.PNG)

**Comment by nxanil** [comment]
@bmukheja 
Could you please provide all the scripts for `nuage_ike_*` so that we can generate the same issue at our end and fix it.

**Comment by bmukheja** [comment]
@nxanil - I'll provide them by EoD tomorrow.

**Comment by bmukheja** [comment]
[es_response.txt](https://github.com/nuagenetworks/visualization-framework/files/2430135/es_response.txt)

@nxanil - Please check this response as you requested. The root cause for this problem is the gte is not being updated, only lte is updated.

**Comment by natabal** [comment]
@nxanil Please address this bug asap.

**Comment by psjawale** [comment]
Verified the fix in latest image. Scroll working fine
