### ISSUE TITLE
Filter Box functionality is broken

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#762]
Hi @nxanil, there have been several issues seen recently with the filter box we use in the tables as well as geomap. Below is the list of issues -

1. Blank window with no search on "selection" search column in geomap/table
2. Delete button not working on the search filter box.
3. When deleting with backspace, data shows up after a while.
4. Some fields are not searchable at all even with correct values. There is no fixed rule when this happens or not.
5. The tick mark, delete button and test are going out of the box
6. The magnifier icon is still full size and appears ugly
7. What is the use of magnifier icon anyways?

Attaching screenshots below. cc @natabal 

![image](https://user-images.githubusercontent.com/15804045/47386540-be079400-d6c1-11e8-86c1-1a324485b92d.png)

**Comment by natabal** [comment]
@nxanil Please make this top priority as we are in the latest stages with 5.3.3 and these are considered blockers! Thanks!
