### ISSUE TITLE
DropDown menu bug

### ISSUE THREAD

**Issue by bmukheja** [nuagenetworks/visualization-framework#764]
There is a drop-down menu for Refresh Interval on viz dashboards to select any of the options. The drop-down menu is giving an option to choose 30 seconds to select as the refresh interval time, but it is not showing it when the option is selected, unlike Inactive option.

![image](https://user-images.githubusercontent.com/15804045/47396253-d639dc00-d6de-11e8-83ed-4ead8e077eb5.png)

**Comment by nxanil** [comment]
@bmukheja 
Fixed in PR #766.
